//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DayNameInBulgarian.Client.DayNameInBulgarianService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DayNameInBulgarianService.IDayNameInBulgarianService")]
    public interface IDayNameInBulgarianService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDayNameInBulgarianService/GetDayOfWeekInBulgarian", ReplyAction="http://tempuri.org/IDayNameInBulgarianService/GetDayOfWeekInBulgarianResponse")]
        string GetDayOfWeekInBulgarian(System.DateTime dateTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDayNameInBulgarianService/GetDayOfWeekInBulgarian", ReplyAction="http://tempuri.org/IDayNameInBulgarianService/GetDayOfWeekInBulgarianResponse")]
        System.Threading.Tasks.Task<string> GetDayOfWeekInBulgarianAsync(System.DateTime dateTime);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDayNameInBulgarianServiceChannel : DayNameInBulgarian.Client.DayNameInBulgarianService.IDayNameInBulgarianService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DayNameInBulgarianServiceClient : System.ServiceModel.ClientBase<DayNameInBulgarian.Client.DayNameInBulgarianService.IDayNameInBulgarianService>, DayNameInBulgarian.Client.DayNameInBulgarianService.IDayNameInBulgarianService {
        
        public DayNameInBulgarianServiceClient() {
        }
        
        public DayNameInBulgarianServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DayNameInBulgarianServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DayNameInBulgarianServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DayNameInBulgarianServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetDayOfWeekInBulgarian(System.DateTime dateTime) {
            return base.Channel.GetDayOfWeekInBulgarian(dateTime);
        }
        
        public System.Threading.Tasks.Task<string> GetDayOfWeekInBulgarianAsync(System.DateTime dateTime) {
            return base.Channel.GetDayOfWeekInBulgarianAsync(dateTime);
        }
    }
}
